name: eco_step
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  path_provider: ^2.1.4
  flutter_native_splash: ^2.4.1
  http: ^1.2.2
  location: ^7.0.0
  geolocator: ^12.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  facebook_auth: ^0.0.3
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.3.0
  firebase_storage: ^12.2.0
  flutter_localization: ^0.2.1
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
#  maplibre_gl: ^0.20.0
  url_launcher: ^6.3.0
  flutter_polyline_points: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7

# Flutter Intl configuration should be at the top level, not inside any dependencies block
#flutter_intl:
#  enabled: true
#  arb_dir: lib/l10n
#  template_arbs:
#    - lib/generated/l10n/intl_en.arb
#    - lib/generated/l10n/intl_af.arb
#    - lib/generated/l10n/intl_ar.arb
#    - lib/generated/l10n/intl_zh.arb
#    - lib/generated/l10n/intl_nl.arb
#    - lib/generated/l10n/intl_fr.arb
#    - lib/generated/l10n/intl_de.arb
#    - lib/generated/l10n/intl_el.arb
#    - lib/generated/l10n/intl_he.arb
#    - lib/generated/l10n/intl_pl.arb
#  output_localization_file: lib/l10n/intl_messages.dart
#  output_localization_file_header: lib/l10n/intl_messages_header.dart
#  output_localization_file_header_path: lib/l10n/intl_messages_header.dart

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/generated/l10n/
