// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALyeyx6v1AC0M7iRy4SlFaAV3sIwBXqTM',
    appId: '1:384320428094:android:7f7be082613e262f1d196f',
    messagingSenderId: '384320428094',
    projectId: 'eco-project-5777b',
    storageBucket: 'eco-project-5777b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkmDjDDGmgKPbNWdCdLgUTQr3I999DlLs',
    appId: '1:384320428094:ios:0c798be35fa8141c1d196f',
    messagingSenderId: '384320428094',
    projectId: 'eco-project-5777b',
    storageBucket: 'eco-project-5777b.appspot.com',
    iosBundleId: 'com.example.ecoStep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkmDjDDGmgKPbNWdCdLgUTQr3I999DlLs',
    appId: '1:384320428094:ios:0c798be35fa8141c1d196f',
    messagingSenderId: '384320428094',
    projectId: 'eco-project-5777b',
    storageBucket: 'eco-project-5777b.appspot.com',
    iosBundleId: 'com.example.ecoStep',
  );
}
